language: node_js
node_js:
  - "stable"
cache: npm
install:
- npm install
script:
- npm run development
script:
- mongodb

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: develop
