language: node_js
node_js:
  - "stable"
cache: npm
install:
- npm install
script:
- npm run build

#this services still not clear if it necesary, please research
services:
 mongodb 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
